create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  cliente_nombre text not null,
  cliente_telefono text not null,
  direccion text not null,
  producto text not null,
  tamano text not null check (tamano in ('pequeno', 'mediano', 'grande')),
  precio integer not null check (precio in (5000, 6000, 7000)),
  metodo_pago text not null default 'efectivo',
  estado text not null default 'pendiente',
  notas text
);

create index if not exists pedidos_created_at_idx on public.pedidos (created_at desc);
