create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  cliente_nombre text not null,
  cliente_telefono text not null,
  direccion text not null,
  producto text not null,
  tamano text not null check (tamano in ('pequeno', 'mediano', 'grande')),
  precio integer not null check (precio in (5000, 6000, 7000)),
  constraint pedidos_size_price_check check (
    (tamano = 'pequeno' and precio = 5000)
    or (tamano = 'mediano' and precio = 6000)
    or (tamano = 'grande' and precio = 7000)
  ),
  metodo_pago text not null default 'efectivo',
  estado text not null default 'pendiente',
  notas text
);

create index if not exists pedidos_created_at_idx on public.pedidos (created_at desc);

alter table public.pedidos enable row level security;

grant usage on schema public to anon;
grant insert on table public.pedidos to anon;
grant select on table public.pedidos to anon;
grant update (estado) on table public.pedidos to anon;
grant delete on table public.pedidos to anon;
grant usage, select on sequence public.pedidos_id_seq to anon;

drop policy if exists pedidos_insert_anon on public.pedidos;
create policy pedidos_insert_anon
on public.pedidos
for insert
to anon
with check (
  metodo_pago = 'efectivo'
  and estado = 'pendiente'
  and (
    (tamano = 'pequeno' and precio = 5000)
    or (tamano = 'mediano' and precio = 6000)
    or (tamano = 'grande' and precio = 7000)
  )
);

drop policy if exists pedidos_select_anon on public.pedidos;
create policy pedidos_select_anon
on public.pedidos
for select
to anon
using (true);

drop policy if exists pedidos_update_estado_anon on public.pedidos;
create policy pedidos_update_estado_anon
on public.pedidos
for update
to anon
using (estado = 'pendiente')
with check (estado = 'entregado');

drop policy if exists pedidos_delete_anon on public.pedidos;
create policy pedidos_delete_anon
on public.pedidos
for delete
to anon
using (true);

create table if not exists public.pqr (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  nombre text not null,
  correo text,
  mensaje text not null check (char_length(mensaje) <= 500)
);

alter table public.pqr add column if not exists correo text;

drop policy if exists pqr_insert_anon on public.pqr;
create policy pqr_insert_anon
on public.pqr
for insert
to anon
with check (
  char_length(mensaje) <= 500
  and correo is not null
  and char_length(trim(correo)) > 5
  and position('@' in correo) > 1
);

create index if not exists pqr_created_at_idx on public.pqr (created_at desc);

alter table public.pqr enable row level security;

grant insert, select on table public.pqr to anon;
grant usage, select on sequence public.pqr_id_seq to anon;

drop policy if exists pqr_select_anon on public.pqr;
create policy pqr_select_anon
on public.pqr
for select
to anon
using (true);

-- =============================================
-- TABLA PEDIDO